// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: SystemStatsService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// каждые send_period секунд выдавать информацию, усреднённую за calc_period секунд
type SystemStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendPeriod uint32 `protobuf:"varint,1,opt,name=send_period,json=sendPeriod,proto3" json:"send_period,omitempty"`
	CalcPeriod uint32 `protobuf:"varint,2,opt,name=calc_period,json=calcPeriod,proto3" json:"calc_period,omitempty"`
}

func (x *SystemStatsRequest) Reset() {
	*x = SystemStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsRequest) ProtoMessage() {}

func (x *SystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsRequest.ProtoReflect.Descriptor instead.
func (*SystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{0}
}

func (x *SystemStatsRequest) GetSendPeriod() uint32 {
	if x != nil {
		return x.SendPeriod
	}
	return 0
}

func (x *SystemStatsRequest) GetCalcPeriod() uint32 {
	if x != nil {
		return x.CalcPeriod
	}
	return 0
}

type SystemStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadAvgStats     *LoadAvgStatsPb     `protobuf:"bytes,1,opt,name=load_avg_stats,json=loadAvgStats,proto3" json:"load_avg_stats,omitempty"`
	CpuStats         *CpuStatsPb         `protobuf:"bytes,2,opt,name=cpu_stats,json=cpuStats,proto3" json:"cpu_stats,omitempty"`
	DisksLoadStats   *DisksLoadStatsPb   `protobuf:"bytes,3,opt,name=disks_load_stats,json=disksLoadStats,proto3" json:"disks_load_stats,omitempty"`
	FilesystemsStats *FilesystemsStatsPb `protobuf:"bytes,4,opt,name=filesystems_stats,json=filesystemsStats,proto3" json:"filesystems_stats,omitempty"`
}

func (x *SystemStatsPb) Reset() {
	*x = SystemStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsPb) ProtoMessage() {}

func (x *SystemStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsPb.ProtoReflect.Descriptor instead.
func (*SystemStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{1}
}

func (x *SystemStatsPb) GetLoadAvgStats() *LoadAvgStatsPb {
	if x != nil {
		return x.LoadAvgStats
	}
	return nil
}

func (x *SystemStatsPb) GetCpuStats() *CpuStatsPb {
	if x != nil {
		return x.CpuStats
	}
	return nil
}

func (x *SystemStatsPb) GetDisksLoadStats() *DisksLoadStatsPb {
	if x != nil {
		return x.DisksLoadStats
	}
	return nil
}

func (x *SystemStatsPb) GetFilesystemsStats() *FilesystemsStatsPb {
	if x != nil {
		return x.FilesystemsStats
	}
	return nil
}

type LoadAvgStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// за 1 минуту
	LoadAvg1 float64 `protobuf:"fixed64,1,opt,name=load_avg1,json=loadAvg1,proto3" json:"load_avg1,omitempty"`
	// за 5 минут
	LoadAvg5 float64 `protobuf:"fixed64,2,opt,name=load_avg5,json=loadAvg5,proto3" json:"load_avg5,omitempty"`
	// за 15 минут
	LoadAvg15 float64 `protobuf:"fixed64,3,opt,name=load_avg15,json=loadAvg15,proto3" json:"load_avg15,omitempty"`
}

func (x *LoadAvgStatsPb) Reset() {
	*x = LoadAvgStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadAvgStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvgStatsPb) ProtoMessage() {}

func (x *LoadAvgStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvgStatsPb.ProtoReflect.Descriptor instead.
func (*LoadAvgStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAvgStatsPb) GetLoadAvg1() float64 {
	if x != nil {
		return x.LoadAvg1
	}
	return 0
}

func (x *LoadAvgStatsPb) GetLoadAvg5() float64 {
	if x != nil {
		return x.LoadAvg5
	}
	return 0
}

func (x *LoadAvgStatsPb) GetLoadAvg15() float64 {
	if x != nil {
		return x.LoadAvg15
	}
	return 0
}

type CpuStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserMode   float64 `protobuf:"fixed64,1,opt,name=user_mode,json=userMode,proto3" json:"user_mode,omitempty"`
	SystemMode float64 `protobuf:"fixed64,2,opt,name=system_mode,json=systemMode,proto3" json:"system_mode,omitempty"`
	Idle       float64 `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *CpuStatsPb) Reset() {
	*x = CpuStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpuStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuStatsPb) ProtoMessage() {}

func (x *CpuStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuStatsPb.ProtoReflect.Descriptor instead.
func (*CpuStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{3}
}

func (x *CpuStatsPb) GetUserMode() float64 {
	if x != nil {
		return x.UserMode
	}
	return 0
}

func (x *CpuStatsPb) GetSystemMode() float64 {
	if x != nil {
		return x.SystemMode
	}
	return 0
}

func (x *CpuStatsPb) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type DisksLoadStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disks []*DiskLoadStatsPb `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
}

func (x *DisksLoadStatsPb) Reset() {
	*x = DisksLoadStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisksLoadStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksLoadStatsPb) ProtoMessage() {}

func (x *DisksLoadStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksLoadStatsPb.ProtoReflect.Descriptor instead.
func (*DisksLoadStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{4}
}

func (x *DisksLoadStatsPb) GetDisks() []*DiskLoadStatsPb {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskLoadStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disk string  `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
	Tps  float64 `protobuf:"fixed64,2,opt,name=tps,proto3" json:"tps,omitempty"`
	Kbs  float64 `protobuf:"fixed64,3,opt,name=kbs,proto3" json:"kbs,omitempty"`
}

func (x *DiskLoadStatsPb) Reset() {
	*x = DiskLoadStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiskLoadStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskLoadStatsPb) ProtoMessage() {}

func (x *DiskLoadStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskLoadStatsPb.ProtoReflect.Descriptor instead.
func (*DiskLoadStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{5}
}

func (x *DiskLoadStatsPb) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

func (x *DiskLoadStatsPb) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskLoadStatsPb) GetKbs() float64 {
	if x != nil {
		return x.Kbs
	}
	return 0
}

type FilesystemsStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filesystems []*FilesystemStatsPb `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
}

func (x *FilesystemsStatsPb) Reset() {
	*x = FilesystemsStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesystemsStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemsStatsPb) ProtoMessage() {}

func (x *FilesystemsStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemsStatsPb.ProtoReflect.Descriptor instead.
func (*FilesystemsStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{6}
}

func (x *FilesystemsStatsPb) GetFilesystems() []*FilesystemStatsPb {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

type FilesystemStatsPb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filesystem       string  `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	MountedOn        string  `protobuf:"bytes,2,opt,name=mounted_on,json=mountedOn,proto3" json:"mounted_on,omitempty"`
	UsedMb           float64 `protobuf:"fixed64,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	UsedPercent      float64 `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	UsedInode        float64 `protobuf:"fixed64,5,opt,name=used_inode,json=usedInode,proto3" json:"used_inode,omitempty"`
	UsedInodePercent float64 `protobuf:"fixed64,6,opt,name=used_inode_percent,json=usedInodePercent,proto3" json:"used_inode_percent,omitempty"`
}

func (x *FilesystemStatsPb) Reset() {
	*x = FilesystemStatsPb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SystemStatsService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesystemStatsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemStatsPb) ProtoMessage() {}

func (x *FilesystemStatsPb) ProtoReflect() protoreflect.Message {
	mi := &file_SystemStatsService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemStatsPb.ProtoReflect.Descriptor instead.
func (*FilesystemStatsPb) Descriptor() ([]byte, []int) {
	return file_SystemStatsService_proto_rawDescGZIP(), []int{7}
}

func (x *FilesystemStatsPb) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *FilesystemStatsPb) GetMountedOn() string {
	if x != nil {
		return x.MountedOn
	}
	return ""
}

func (x *FilesystemStatsPb) GetUsedMb() float64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *FilesystemStatsPb) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *FilesystemStatsPb) GetUsedInode() float64 {
	if x != nil {
		return x.UsedInode
	}
	return 0
}

func (x *FilesystemStatsPb) GetUsedInodePercent() float64 {
	if x != nil {
		return x.UsedInodePercent
	}
	return 0
}

var File_SystemStatsService_proto protoreflect.FileDescriptor

var file_SystemStatsService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x22, 0x56, 0x0a, 0x12, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x63,
	0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63,
	0x61, 0x6c, 0x63, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0x87, 0x02, 0x0a, 0x0d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x12, 0x3b, 0x0a, 0x0e, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x61, 0x76, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x41, 0x76, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x52, 0x0c, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x76, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2e, 0x43, 0x70, 0x75, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x52, 0x08,
	0x63, 0x70, 0x75, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x6b,
	0x73, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x73,
	0x4c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x52, 0x0e, 0x64, 0x69, 0x73,
	0x6b, 0x73, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x46, 0x0a, 0x11, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50,
	0x62, 0x52, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x22, 0x69, 0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x67, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x50, 0x62, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x61, 0x76,
	0x67, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76,
	0x67, 0x31, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x61, 0x76, 0x67, 0x35, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x67, 0x35, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x61, 0x76, 0x67, 0x31, 0x35, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x67, 0x31, 0x35, 0x22, 0x5e,
	0x0a, 0x0a, 0x43, 0x70, 0x75, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x12, 0x1b, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x64,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x22, 0x40,
	0x0a, 0x10, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x50, 0x62, 0x12, 0x2c, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x4c, 0x6f,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73,
	0x22, 0x49, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x6b, 0x4c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x50, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x74, 0x70, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x62, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6b, 0x62, 0x73, 0x22, 0x50, 0x0a, 0x12, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50,
	0x62, 0x12, 0x3a, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62,
	0x52, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xdb, 0x01,
	0x0a, 0x11, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x50, 0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64,
	0x4f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x62, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x75, 0x73, 0x65, 0x64, 0x4d, 0x62, 0x12, 0x21, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a,
	0x12, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x75, 0x73, 0x65, 0x64, 0x49,
	0x6e, 0x6f, 0x64, 0x65, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x32, 0x5f, 0x0a, 0x12, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x49, 0x0a, 0x12, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x62, 0x22, 0x00, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SystemStatsService_proto_rawDescOnce sync.Once
	file_SystemStatsService_proto_rawDescData = file_SystemStatsService_proto_rawDesc
)

func file_SystemStatsService_proto_rawDescGZIP() []byte {
	file_SystemStatsService_proto_rawDescOnce.Do(func() {
		file_SystemStatsService_proto_rawDescData = protoimpl.X.CompressGZIP(file_SystemStatsService_proto_rawDescData)
	})
	return file_SystemStatsService_proto_rawDescData
}

var file_SystemStatsService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_SystemStatsService_proto_goTypes = []any{
	(*SystemStatsRequest)(nil), // 0: stats.SystemStatsRequest
	(*SystemStatsPb)(nil),      // 1: stats.SystemStatsPb
	(*LoadAvgStatsPb)(nil),     // 2: stats.LoadAvgStatsPb
	(*CpuStatsPb)(nil),         // 3: stats.CpuStatsPb
	(*DisksLoadStatsPb)(nil),   // 4: stats.DisksLoadStatsPb
	(*DiskLoadStatsPb)(nil),    // 5: stats.DiskLoadStatsPb
	(*FilesystemsStatsPb)(nil), // 6: stats.FilesystemsStatsPb
	(*FilesystemStatsPb)(nil),  // 7: stats.FilesystemStatsPb
}
var file_SystemStatsService_proto_depIdxs = []int32{
	2, // 0: stats.SystemStatsPb.load_avg_stats:type_name -> stats.LoadAvgStatsPb
	3, // 1: stats.SystemStatsPb.cpu_stats:type_name -> stats.CpuStatsPb
	4, // 2: stats.SystemStatsPb.disks_load_stats:type_name -> stats.DisksLoadStatsPb
	6, // 3: stats.SystemStatsPb.filesystems_stats:type_name -> stats.FilesystemsStatsPb
	5, // 4: stats.DisksLoadStatsPb.disks:type_name -> stats.DiskLoadStatsPb
	7, // 5: stats.FilesystemsStatsPb.filesystems:type_name -> stats.FilesystemStatsPb
	0, // 6: stats.SystemStatsService.ObserveSystemStats:input_type -> stats.SystemStatsRequest
	1, // 7: stats.SystemStatsService.ObserveSystemStats:output_type -> stats.SystemStatsPb
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_SystemStatsService_proto_init() }
func file_SystemStatsService_proto_init() {
	if File_SystemStatsService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SystemStatsService_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SystemStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SystemStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LoadAvgStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CpuStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DisksLoadStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DiskLoadStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FilesystemsStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SystemStatsService_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FilesystemStatsPb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SystemStatsService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SystemStatsService_proto_goTypes,
		DependencyIndexes: file_SystemStatsService_proto_depIdxs,
		MessageInfos:      file_SystemStatsService_proto_msgTypes,
	}.Build()
	File_SystemStatsService_proto = out.File
	file_SystemStatsService_proto_rawDesc = nil
	file_SystemStatsService_proto_goTypes = nil
	file_SystemStatsService_proto_depIdxs = nil
}
