// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CommandExecutor is an autogenerated mock type for the CommandExecutor type
type CommandExecutor struct {
	mock.Mock
}

type CommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *CommandExecutor) EXPECT() *CommandExecutor_Expecter {
	return &CommandExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name, arg
func (_m *CommandExecutor) Execute(name string, arg ...string) ([]byte, error) {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) ([]byte, error)); ok {
		return rf(name, arg...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) []byte); ok {
		r0 = rf(name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(name, arg...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommandExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CommandExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
//   - arg ...string
func (_e *CommandExecutor_Expecter) Execute(name interface{}, arg ...interface{}) *CommandExecutor_Execute_Call {
	return &CommandExecutor_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{name}, arg...)...)}
}

func (_c *CommandExecutor_Execute_Call) Run(run func(name string, arg ...string)) *CommandExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *CommandExecutor_Execute_Call) Return(_a0 []byte, _a1 error) *CommandExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommandExecutor_Execute_Call) RunAndReturn(run func(string, ...string) ([]byte, error)) *CommandExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommandExecutor creates a new instance of CommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandExecutor {
	mock := &CommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
