# Logger config
logger:
  level: "DEBUG"
# GRPC server config
grpcServer:
  port: ${GRPC_SERVER_PORT}
# App config
app:
  collectCronSpec: "* * * * * *" # каждую секунду
  collectTimeout: 500ms
  metrics: # какие метрики будут собираться
    la: true
    cpu: true
    disksLoad: true
    filesystem: true